2019-02-18 17:24:16.301 [user_provider] [main] INFO  [org.springframework.context.annotation.AnnotationConfigApplicationContext] -Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@3c41ed1d: startup date [Mon Feb 18 17:24:16 CST 2019]; root of context hierarchy
2019-02-18 17:24:16.709 [user_provider] [main] INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] -JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-02-18 17:24:16.746 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$37cef890] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:24:16.944 [user_provider] [main] INFO  [cn.qyd.blogroom.user.UserServiceProvider] -The following profiles are active: dev
2019-02-18 17:24:16.963 [user_provider] [main] INFO  [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext] -Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@265adfad: startup date [Mon Feb 18 17:24:16 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@3c41ed1d
2019-02-18 17:24:18.118 [user_provider] [main] INFO  [org.springframework.cloud.context.scope.GenericScope] -BeanFactory id=75e97e42-5bb2-380c-805c-0ba7c56d2084
2019-02-18 17:24:18.150 [user_provider] [main] INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] -JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-02-18 17:24:18.260 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$1bb4f593] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:24:18.299 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$37cef890] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:24:18.562 [user_provider] [main] INFO  [org.springframework.boot.web.embedded.tomcat.TomcatWebServer] -Tomcat initialized with port(s): 8091 (http)
2019-02-18 17:24:18.576 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Initializing ProtocolHandler ["http-nio-8091"]
2019-02-18 17:24:18.584 [user_provider] [main] INFO  [org.apache.catalina.core.StandardService] -Starting service [Tomcat]
2019-02-18 17:24:18.584 [user_provider] [main] INFO  [org.apache.catalina.core.StandardEngine] -Starting Servlet Engine: Apache Tomcat/8.5.32
2019-02-18 17:24:18.587 [user_provider] [localhost-startStop-1] INFO  [org.apache.catalina.core.AprLifecycleListener] -The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
2019-02-18 17:24:18.669 [user_provider] [localhost-startStop-1] INFO  [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]] -Initializing Spring embedded WebApplicationContext
2019-02-18 17:24:18.669 [user_provider] [localhost-startStop-1] INFO  [org.springframework.web.context.ContextLoader] -Root WebApplicationContext: initialization completed in 1706 ms
2019-02-18 17:24:18.890 [user_provider] [localhost-startStop-1] WARN  [com.netflix.config.sources.URLConfigurationSource] -No URLs will be polled as dynamic configuration sources.
2019-02-18 17:24:18.890 [user_provider] [localhost-startStop-1] INFO  [com.netflix.config.sources.URLConfigurationSource] -To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-02-18 17:24:18.896 [user_provider] [localhost-startStop-1] INFO  [com.netflix.config.DynamicPropertyFactory] -DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@223fd5
2019-02-18 17:24:19.555 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'characterEncodingFilter' to: [/*]
2019-02-18 17:24:19.555 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'webMvcMetricsFilter' to: [/*]
2019-02-18 17:24:19.556 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-02-18 17:24:19.556 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-02-18 17:24:19.556 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'requestContextFilter' to: [/*]
2019-02-18 17:24:19.556 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'httpTraceFilter' to: [/*]
2019-02-18 17:24:19.556 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.ServletRegistrationBean] -Servlet dispatcherServlet mapped to [/]
2019-02-18 17:24:19.785 [user_provider] [main] INFO  [com.alibaba.druid.pool.DruidDataSource] -{dataSource-1} inited
2019-02-18 17:24:24.215 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:24:28.233 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:24:32.765 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:24:37.292 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:24:41.813 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:24:46.339 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:24:50.851 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:24:55.415 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:24:59.926 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:25:04.460 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:25:08.976 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:25:13.492 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:25:18.014 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:25:22.524 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:25:27.055 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:25:31.569 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 13 common frames omitted
2019-02-18 17:25:36.078 [user_provider] [Druid-ConnectionPool-Create-742672037] ERROR [com.alibaba.druid.pool.DruidDataSource] -create connection SQLException, url: jdbc:mysql://localhost:3306/blogroom-user?characterEncoding=utf8&useSSL=true&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.GeneratedConstructorAccessor56.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor54.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'blogroom-user'
	at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 12 common frames omitted
2019-02-18 17:25:40.581 [user_provider] [main] INFO  [org.springframework.context.annotation.AnnotationConfigApplicationContext] -Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@5b12b668: startup date [Mon Feb 18 17:25:40 CST 2019]; root of context hierarchy
2019-02-18 17:25:41.070 [user_provider] [main] INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] -JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-02-18 17:25:41.123 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$468755f7] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:25:41.332 [user_provider] [main] INFO  [cn.qyd.blogroom.user.UserServiceProvider] -The following profiles are active: dev
2019-02-18 17:25:41.343 [user_provider] [main] INFO  [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext] -Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@38089a5a: startup date [Mon Feb 18 17:25:41 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@5b12b668
2019-02-18 17:25:42.318 [user_provider] [main] INFO  [org.springframework.cloud.context.scope.GenericScope] -BeanFactory id=75e97e42-5bb2-380c-805c-0ba7c56d2084
2019-02-18 17:25:42.340 [user_provider] [main] INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] -JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-02-18 17:25:42.441 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$2a6d52fa] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:25:42.489 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$468755f7] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:25:42.751 [user_provider] [main] INFO  [org.springframework.boot.web.embedded.tomcat.TomcatWebServer] -Tomcat initialized with port(s): 8091 (http)
2019-02-18 17:25:42.761 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Initializing ProtocolHandler ["http-nio-8091"]
2019-02-18 17:25:42.769 [user_provider] [main] INFO  [org.apache.catalina.core.StandardService] -Starting service [Tomcat]
2019-02-18 17:25:42.769 [user_provider] [main] INFO  [org.apache.catalina.core.StandardEngine] -Starting Servlet Engine: Apache Tomcat/8.5.32
2019-02-18 17:25:42.773 [user_provider] [localhost-startStop-1] INFO  [org.apache.catalina.core.AprLifecycleListener] -The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
2019-02-18 17:25:42.848 [user_provider] [localhost-startStop-1] INFO  [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]] -Initializing Spring embedded WebApplicationContext
2019-02-18 17:25:42.849 [user_provider] [localhost-startStop-1] INFO  [org.springframework.web.context.ContextLoader] -Root WebApplicationContext: initialization completed in 1506 ms
2019-02-18 17:25:43.086 [user_provider] [localhost-startStop-1] WARN  [com.netflix.config.sources.URLConfigurationSource] -No URLs will be polled as dynamic configuration sources.
2019-02-18 17:25:43.086 [user_provider] [localhost-startStop-1] INFO  [com.netflix.config.sources.URLConfigurationSource] -To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-02-18 17:25:43.091 [user_provider] [localhost-startStop-1] INFO  [com.netflix.config.DynamicPropertyFactory] -DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@3c6742af
2019-02-18 17:25:43.753 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'characterEncodingFilter' to: [/*]
2019-02-18 17:25:43.753 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'webMvcMetricsFilter' to: [/*]
2019-02-18 17:25:43.753 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-02-18 17:25:43.753 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-02-18 17:25:43.753 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'requestContextFilter' to: [/*]
2019-02-18 17:25:43.753 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'httpTraceFilter' to: [/*]
2019-02-18 17:25:43.753 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.ServletRegistrationBean] -Servlet dispatcherServlet mapped to [/]
2019-02-18 17:25:43.854 [user_provider] [main] INFO  [com.alibaba.druid.pool.DruidDataSource] -{dataSource-1} inited
2019-02-18 17:25:44.156 [user_provider] [main] INFO  [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean] -Building JPA container EntityManagerFactory for persistence unit 'default'
2019-02-18 17:25:44.191 [user_provider] [main] INFO  [org.hibernate.jpa.internal.util.LogHelper] -HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2019-02-18 17:25:44.326 [user_provider] [main] INFO  [org.hibernate.Version] -HHH000412: Hibernate Core {5.2.17.Final}
2019-02-18 17:25:44.328 [user_provider] [main] INFO  [org.hibernate.cfg.Environment] -HHH000206: hibernate.properties not found
2019-02-18 17:25:44.367 [user_provider] [main] INFO  [org.hibernate.annotations.common.Version] -HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
2019-02-18 17:25:44.629 [user_provider] [main] INFO  [org.hibernate.dialect.Dialect] -HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
2019-02-18 17:25:45.025 [user_provider] [main] INFO  [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean] -Initialized JPA EntityManagerFactory for persistence unit 'default'
2019-02-18 17:25:45.492 [user_provider] [main] WARN  [org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration] -spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2019-02-18 17:25:45.569 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/getUser],methods=[GET]}" onto public java.lang.String cn.qyd.blogroom.user.controller.UserController.getUser()
2019-02-18 17:25:45.572 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/swagger-resources/configuration/security]}" onto public org.springframework.http.ResponseEntity<springfox.documentation.swagger.web.SecurityConfiguration> springfox.documentation.swagger.web.ApiResourceController.securityConfiguration()
2019-02-18 17:25:45.573 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/swagger-resources/configuration/ui]}" onto public org.springframework.http.ResponseEntity<springfox.documentation.swagger.web.UiConfiguration> springfox.documentation.swagger.web.ApiResourceController.uiConfiguration()
2019-02-18 17:25:45.574 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/swagger-resources]}" onto public org.springframework.http.ResponseEntity<java.util.List<springfox.documentation.swagger.web.SwaggerResource>> springfox.documentation.swagger.web.ApiResourceController.swaggerResources()
2019-02-18 17:25:45.578 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-02-18 17:25:45.578 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-02-18 17:25:45.706 [user_provider] [main] INFO  [org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver] -Exposing 2 endpoint(s) beneath base path '/actuator'
2019-02-18 17:25:45.721 [user_provider] [main] INFO  [org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping] -Mapped "{[/actuator/health],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)
2019-02-18 17:25:45.722 [user_provider] [main] INFO  [org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping] -Mapped "{[/actuator/info],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)
2019-02-18 17:25:45.723 [user_provider] [main] INFO  [org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping] -Mapped "{[/actuator],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto protected java.util.Map<java.lang.String, java.util.Map<java.lang.String, org.springframework.boot.actuate.endpoint.web.Link>> org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping.links(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-02-18 17:25:45.875 [user_provider] [main] INFO  [springfox.documentation.spring.web.PropertySourcedRequestMappingHandlerMapping] -Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
2019-02-18 17:25:45.899 [user_provider] [main] WARN  [com.netflix.config.sources.URLConfigurationSource] -No URLs will be polled as dynamic configuration sources.
2019-02-18 17:25:45.899 [user_provider] [main] INFO  [com.netflix.config.sources.URLConfigurationSource] -To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-02-18 17:25:45.969 [user_provider] [main] INFO  [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping] -Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-02-18 17:25:46.185 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter] -Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@38089a5a: startup date [Mon Feb 18 17:25:41 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@5b12b668
2019-02-18 17:25:46.250 [user_provider] [main] INFO  [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping] -Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-02-18 17:25:46.250 [user_provider] [main] INFO  [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping] -Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-02-18 17:25:46.944 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Registering beans for JMX exposure on startup
2019-02-18 17:25:46.946 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Bean with name 'dataSource' has been autodetected for JMX exposure
2019-02-18 17:25:46.955 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Bean with name 'environmentManager' has been autodetected for JMX exposure
2019-02-18 17:25:46.956 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Bean with name 'refreshScope' has been autodetected for JMX exposure
2019-02-18 17:25:46.957 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2019-02-18 17:25:46.961 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2019-02-18 17:25:46.968 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2019-02-18 17:25:46.978 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=38089a5a,type=ConfigurationPropertiesRebinder]
2019-02-18 17:25:46.985 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Located MBean 'dataSource': registering with JMX server as MBean [com.alibaba.druid.pool:name=dataSource,type=DruidDataSource]
2019-02-18 17:25:46.991 [user_provider] [main] INFO  [org.springframework.context.support.DefaultLifecycleProcessor] -Starting beans in phase 0
2019-02-18 17:25:47.009 [user_provider] [main] INFO  [org.springframework.cloud.netflix.eureka.InstanceInfoFactory] -Setting initial instance status as: STARTING
2019-02-18 17:25:47.037 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Initializing Eureka in region us-east-1
2019-02-18 17:25:47.194 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using JSON encoding codec LegacyJacksonJson
2019-02-18 17:25:47.194 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using JSON decoding codec LegacyJacksonJson
2019-02-18 17:25:47.576 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using XML encoding codec XStreamXml
2019-02-18 17:25:47.576 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using XML decoding codec XStreamXml
2019-02-18 17:25:47.829 [user_provider] [main] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:25:47.854 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Disable delta property : false
2019-02-18 17:25:47.854 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Single vip registry refresh property : null
2019-02-18 17:25:47.854 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Force full registry fetch : false
2019-02-18 17:25:47.854 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Application is null : false
2019-02-18 17:25:47.854 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Registered Applications size is zero : true
2019-02-18 17:25:47.854 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Application version is -1: true
2019-02-18 17:25:47.854 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Getting all instance registry info from the eureka server
2019-02-18 17:25:48.207 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -The response status is 200
2019-02-18 17:25:48.209 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Starting heartbeat executor: renew interval is: 30
2019-02-18 17:25:48.211 [user_provider] [main] INFO  [com.netflix.discovery.InstanceInfoReplicator] -InstanceInfoReplicator onDemand update allowed rate per min is 4
2019-02-18 17:25:48.221 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Discovery Client initialized at timestamp 1550481948220 with initial instances count: 0
2019-02-18 17:25:48.226 [user_provider] [main] INFO  [org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry] -Registering application USER-PROVIDER with eureka with status UP
2019-02-18 17:25:48.227 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Saw local status change event StatusChangeEvent [timestamp=1550481948227, current=UP, previous=STARTING]
2019-02-18 17:25:48.233 [user_provider] [DiscoveryClient-InstanceInfoReplicator-0] INFO  [com.netflix.discovery.DiscoveryClient] -DiscoveryClient_USER-PROVIDER/192.168.1.167:8091: registering service...
2019-02-18 17:25:48.238 [user_provider] [main] INFO  [org.springframework.context.support.DefaultLifecycleProcessor] -Starting beans in phase 2147483647
2019-02-18 17:25:48.239 [user_provider] [main] INFO  [springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper] -Context refreshed
2019-02-18 17:25:48.271 [user_provider] [main] INFO  [springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper] -Found 1 custom documentation plugin(s)
2019-02-18 17:25:48.370 [user_provider] [main] INFO  [springfox.documentation.spring.web.scanners.ApiListingReferenceScanner] -Scanning for api listing references
2019-02-18 17:25:48.492 [user_provider] [DiscoveryClient-InstanceInfoReplicator-0] INFO  [com.netflix.discovery.DiscoveryClient] -DiscoveryClient_USER-PROVIDER/192.168.1.167:8091 - registration status: 204
2019-02-18 17:25:48.570 [user_provider] [main] INFO  [springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator] -Generating unique operation named: handleUsingGET_1
2019-02-18 17:25:48.676 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Starting ProtocolHandler ["http-nio-8091"]
2019-02-18 17:25:48.682 [user_provider] [main] INFO  [org.apache.tomcat.util.net.NioSelectorPool] -Using a shared selector for servlet write/read
2019-02-18 17:25:48.715 [user_provider] [main] INFO  [org.springframework.boot.web.embedded.tomcat.TomcatWebServer] -Tomcat started on port(s): 8091 (http) with context path ''
2019-02-18 17:25:48.718 [user_provider] [main] INFO  [org.springframework.cloud.netflix.eureka.serviceregistry.EurekaAutoServiceRegistration] -Updating port to 8091
2019-02-18 17:25:48.721 [user_provider] [main] INFO  [cn.qyd.blogroom.user.UserServiceProvider] -Started UserServiceProvider in 8.928 seconds (JVM running for 9.621)
2019-02-18 17:25:49.163 [user_provider] [RMI TCP Connection(12)-127.0.0.1] INFO  [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]] -Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-02-18 17:25:49.164 [user_provider] [RMI TCP Connection(12)-127.0.0.1] INFO  [org.springframework.web.servlet.DispatcherServlet] -FrameworkServlet 'dispatcherServlet': initialization started
2019-02-18 17:25:49.188 [user_provider] [RMI TCP Connection(12)-127.0.0.1] INFO  [org.springframework.web.servlet.DispatcherServlet] -FrameworkServlet 'dispatcherServlet': initialization completed in 23 ms
2019-02-18 17:26:18.210 [user_provider] [DiscoveryClient-CacheRefreshExecutor-0] INFO  [com.netflix.discovery.DiscoveryClient] -Disable delta property : false
2019-02-18 17:26:18.210 [user_provider] [DiscoveryClient-CacheRefreshExecutor-0] INFO  [com.netflix.discovery.DiscoveryClient] -Single vip registry refresh property : null
2019-02-18 17:26:18.210 [user_provider] [DiscoveryClient-CacheRefreshExecutor-0] INFO  [com.netflix.discovery.DiscoveryClient] -Force full registry fetch : false
2019-02-18 17:26:18.210 [user_provider] [DiscoveryClient-CacheRefreshExecutor-0] INFO  [com.netflix.discovery.DiscoveryClient] -Application is null : false
2019-02-18 17:26:18.210 [user_provider] [DiscoveryClient-CacheRefreshExecutor-0] INFO  [com.netflix.discovery.DiscoveryClient] -Registered Applications size is zero : true
2019-02-18 17:26:18.211 [user_provider] [DiscoveryClient-CacheRefreshExecutor-0] INFO  [com.netflix.discovery.DiscoveryClient] -Application version is -1: false
2019-02-18 17:26:18.211 [user_provider] [DiscoveryClient-CacheRefreshExecutor-0] INFO  [com.netflix.discovery.DiscoveryClient] -Getting all instance registry info from the eureka server
2019-02-18 17:26:18.294 [user_provider] [DiscoveryClient-CacheRefreshExecutor-0] INFO  [com.netflix.discovery.DiscoveryClient] -The response status is 200
2019-02-18 17:26:34.864 [user_provider] [main] INFO  [org.springframework.context.annotation.AnnotationConfigApplicationContext] -Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@69453e37: startup date [Mon Feb 18 17:26:34 CST 2019]; root of context hierarchy
2019-02-18 17:26:35.185 [user_provider] [main] INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] -JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-02-18 17:26:35.220 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$d1394f77] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:26:35.418 [user_provider] [main] INFO  [cn.qyd.blogroom.console.ConsoleApp] -The following profiles are active: dev
2019-02-18 17:26:35.427 [user_provider] [main] INFO  [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext] -Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@55493582: startup date [Mon Feb 18 17:26:35 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@69453e37
2019-02-18 17:26:35.913 [user_provider] [main] INFO  [org.springframework.cloud.context.scope.GenericScope] -BeanFactory id=9979f664-36d6-3209-ab02-0281b97f306e
2019-02-18 17:26:35.924 [user_provider] [main] INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] -JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-02-18 17:26:35.979 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$d1394f77] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:26:36.208 [user_provider] [main] INFO  [org.springframework.boot.web.embedded.tomcat.TomcatWebServer] -Tomcat initialized with port(s): 8091 (http)
2019-02-18 17:26:36.217 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Initializing ProtocolHandler ["http-nio-8091"]
2019-02-18 17:26:36.223 [user_provider] [main] INFO  [org.apache.catalina.core.StandardService] -Starting service [Tomcat]
2019-02-18 17:26:36.224 [user_provider] [main] INFO  [org.apache.catalina.core.StandardEngine] -Starting Servlet Engine: Apache Tomcat/8.5.32
2019-02-18 17:26:36.227 [user_provider] [localhost-startStop-1] INFO  [org.apache.catalina.core.AprLifecycleListener] -The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
2019-02-18 17:26:36.287 [user_provider] [localhost-startStop-1] INFO  [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]] -Initializing Spring embedded WebApplicationContext
2019-02-18 17:26:36.287 [user_provider] [localhost-startStop-1] INFO  [org.springframework.web.context.ContextLoader] -Root WebApplicationContext: initialization completed in 860 ms
2019-02-18 17:26:36.320 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.ServletRegistrationBean] -Servlet dispatcherServlet mapped to [/]
2019-02-18 17:26:36.323 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'characterEncodingFilter' to: [/*]
2019-02-18 17:26:36.324 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-02-18 17:26:36.324 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-02-18 17:26:36.324 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'requestContextFilter' to: [/*]
2019-02-18 17:26:36.362 [user_provider] [main] WARN  [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext] -Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testController': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'author.name' in value "${author.name}"
2019-02-18 17:26:36.363 [user_provider] [main] INFO  [org.apache.catalina.core.StandardService] -Stopping service [Tomcat]
2019-02-18 17:26:36.372 [user_provider] [main] INFO  [org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener] -

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-02-18 17:26:36.377 [user_provider] [main] ERROR [org.springframework.boot.SpringApplication] -Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testController': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'author.name' in value "${author.name}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:378)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:572)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at cn.qyd.blogroom.console.ConsoleApp.main(ConsoleApp.java:17)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'author.name' in value "${author.name}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:172)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:237)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:211)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:839)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1083)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:583)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:91)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:372)
	... 17 common frames omitted
2019-02-18 17:27:39.282 [user_provider] [main] INFO  [org.springframework.context.annotation.AnnotationConfigApplicationContext] -Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@2aceadd4: startup date [Mon Feb 18 17:27:39 CST 2019]; root of context hierarchy
2019-02-18 17:27:39.571 [user_provider] [main] INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] -JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-02-18 17:27:39.616 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$c06e47c8] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:27:40.826 [user_provider] [main] INFO  [cn.qyd.blogroom.console.ConsoleApp] -The following profiles are active: dev
2019-02-18 17:27:40.835 [user_provider] [main] INFO  [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext] -Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@2ef14fe: startup date [Mon Feb 18 17:27:40 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@2aceadd4
2019-02-18 17:27:41.272 [user_provider] [main] INFO  [org.springframework.cloud.context.scope.GenericScope] -BeanFactory id=9979f664-36d6-3209-ab02-0281b97f306e
2019-02-18 17:27:41.282 [user_provider] [main] INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] -JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-02-18 17:27:41.342 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$c06e47c8] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:27:41.582 [user_provider] [main] INFO  [org.springframework.boot.web.embedded.tomcat.TomcatWebServer] -Tomcat initialized with port(s): 8091 (http)
2019-02-18 17:27:41.591 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Initializing ProtocolHandler ["http-nio-8091"]
2019-02-18 17:27:41.597 [user_provider] [main] INFO  [org.apache.catalina.core.StandardService] -Starting service [Tomcat]
2019-02-18 17:27:41.597 [user_provider] [main] INFO  [org.apache.catalina.core.StandardEngine] -Starting Servlet Engine: Apache Tomcat/8.5.32
2019-02-18 17:27:41.600 [user_provider] [localhost-startStop-1] INFO  [org.apache.catalina.core.AprLifecycleListener] -The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
2019-02-18 17:27:41.667 [user_provider] [localhost-startStop-1] INFO  [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]] -Initializing Spring embedded WebApplicationContext
2019-02-18 17:27:41.668 [user_provider] [localhost-startStop-1] INFO  [org.springframework.web.context.ContextLoader] -Root WebApplicationContext: initialization completed in 833 ms
2019-02-18 17:27:41.703 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.ServletRegistrationBean] -Servlet dispatcherServlet mapped to [/]
2019-02-18 17:27:41.706 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'characterEncodingFilter' to: [/*]
2019-02-18 17:27:41.706 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-02-18 17:27:41.707 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-02-18 17:27:41.707 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'requestContextFilter' to: [/*]
2019-02-18 17:27:41.760 [user_provider] [main] WARN  [com.netflix.config.sources.URLConfigurationSource] -No URLs will be polled as dynamic configuration sources.
2019-02-18 17:27:41.760 [user_provider] [main] INFO  [com.netflix.config.sources.URLConfigurationSource] -To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-02-18 17:27:41.762 [user_provider] [main] WARN  [com.netflix.config.sources.URLConfigurationSource] -No URLs will be polled as dynamic configuration sources.
2019-02-18 17:27:41.762 [user_provider] [main] INFO  [com.netflix.config.sources.URLConfigurationSource] -To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-02-18 17:27:41.834 [user_provider] [main] INFO  [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping] -Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-02-18 17:27:41.961 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter] -Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@2ef14fe: startup date [Mon Feb 18 17:27:40 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@2aceadd4
2019-02-18 17:27:42.003 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/getAuthor],methods=[GET]}" onto public java.lang.String cn.qyd.blogroom.console.controller.TestController.getAuthor()
2019-02-18 17:27:42.003 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/getUser],methods=[GET]}" onto public java.lang.String cn.qyd.blogroom.console.controller.TestController.getUser()
2019-02-18 17:27:42.007 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-02-18 17:27:42.007 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-02-18 17:27:42.026 [user_provider] [main] INFO  [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping] -Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-02-18 17:27:42.026 [user_provider] [main] INFO  [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping] -Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-02-18 17:27:42.578 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Registering beans for JMX exposure on startup
2019-02-18 17:27:42.584 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2019-02-18 17:27:42.584 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Bean with name 'environmentManager' has been autodetected for JMX exposure
2019-02-18 17:27:42.585 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Bean with name 'refreshScope' has been autodetected for JMX exposure
2019-02-18 17:27:42.587 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2019-02-18 17:27:42.595 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2019-02-18 17:27:42.601 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=2ef14fe,type=ConfigurationPropertiesRebinder]
2019-02-18 17:27:42.607 [user_provider] [main] INFO  [org.springframework.context.support.DefaultLifecycleProcessor] -Starting beans in phase 0
2019-02-18 17:27:42.616 [user_provider] [main] INFO  [org.springframework.cloud.netflix.eureka.InstanceInfoFactory] -Setting initial instance status as: STARTING
2019-02-18 17:27:42.634 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Initializing Eureka in region us-east-1
2019-02-18 17:27:42.784 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using JSON encoding codec LegacyJacksonJson
2019-02-18 17:27:42.785 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using JSON decoding codec LegacyJacksonJson
2019-02-18 17:27:42.886 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using XML encoding codec XStreamXml
2019-02-18 17:27:42.887 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using XML decoding codec XStreamXml
2019-02-18 17:27:43.046 [user_provider] [main] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:27:43.056 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Disable delta property : false
2019-02-18 17:27:43.056 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Single vip registry refresh property : null
2019-02-18 17:27:43.057 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Force full registry fetch : false
2019-02-18 17:27:43.057 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Application is null : false
2019-02-18 17:27:43.057 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Registered Applications size is zero : true
2019-02-18 17:27:43.057 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Application version is -1: true
2019-02-18 17:27:43.057 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Getting all instance registry info from the eureka server
2019-02-18 17:27:43.163 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -The response status is 200
2019-02-18 17:27:43.164 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Starting heartbeat executor: renew interval is: 30
2019-02-18 17:27:43.166 [user_provider] [main] INFO  [com.netflix.discovery.InstanceInfoReplicator] -InstanceInfoReplicator onDemand update allowed rate per min is 4
2019-02-18 17:27:43.169 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Discovery Client initialized at timestamp 1550482063168 with initial instances count: 1
2019-02-18 17:27:43.171 [user_provider] [main] INFO  [org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry] -Registering application BLOGROOM-CONSOLE with eureka with status UP
2019-02-18 17:27:43.172 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Saw local status change event StatusChangeEvent [timestamp=1550482063172, current=UP, previous=STARTING]
2019-02-18 17:27:43.175 [user_provider] [DiscoveryClient-InstanceInfoReplicator-0] INFO  [com.netflix.discovery.DiscoveryClient] -DiscoveryClient_BLOGROOM-CONSOLE/192.168.1.167:8091: registering service...
2019-02-18 17:27:43.186 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Starting ProtocolHandler ["http-nio-8091"]
2019-02-18 17:27:43.191 [user_provider] [main] ERROR [org.apache.catalina.core.StandardService] -Failed to start connector [Connector[HTTP/1.1-8091]]
org.apache.catalina.LifecycleException: Failed to start component [Connector[HTTP/1.1-8091]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:256)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:198)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:300)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at cn.qyd.blogroom.console.ConsoleApp.main(ConsoleApp.java:17)
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1020)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 13 common frames omitted
Caused by: java.net.BindException: 地址已在使用
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210)
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1150)
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:591)
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1018)
	... 14 common frames omitted
2019-02-18 17:27:43.194 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Pausing ProtocolHandler ["http-nio-8091"]
2019-02-18 17:27:43.195 [user_provider] [main] INFO  [org.apache.catalina.core.StandardService] -Stopping service [Tomcat]
2019-02-18 17:27:43.200 [user_provider] [main] INFO  [org.apache.catalina.util.LifecycleBase] -The stop() method was called on component [StandardServer[-1]] after stop() had already been called. The second call will be ignored.
2019-02-18 17:27:43.200 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Stopping ProtocolHandler ["http-nio-8091"]
2019-02-18 17:27:43.200 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Destroying ProtocolHandler ["http-nio-8091"]
2019-02-18 17:27:43.202 [user_provider] [main] INFO  [org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener] -

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-02-18 17:27:43.205 [user_provider] [main] ERROR [org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter] -

***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 8091 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 8091, or configure this application to listen on another port.

2019-02-18 17:27:43.205 [user_provider] [main] INFO  [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext] -Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@2ef14fe: startup date [Mon Feb 18 17:27:40 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@2aceadd4
2019-02-18 17:27:43.206 [user_provider] [main] INFO  [org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry] -Unregistering application BLOGROOM-CONSOLE with eureka with status DOWN
2019-02-18 17:27:43.206 [user_provider] [main] WARN  [com.netflix.discovery.DiscoveryClient] -Saw local status change event StatusChangeEvent [timestamp=1550482063206, current=DOWN, previous=UP]
2019-02-18 17:27:43.207 [user_provider] [main] INFO  [org.springframework.context.support.DefaultLifecycleProcessor] -Stopping beans in phase 0
2019-02-18 17:27:43.208 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Unregistering JMX-exposed beans on shutdown
2019-02-18 17:27:43.209 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Unregistering JMX-exposed beans
2019-02-18 17:27:43.210 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Shutting down DiscoveryClient ...
2019-02-18 17:27:43.210 [user_provider] [DiscoveryClient-InstanceInfoReplicator-0] INFO  [com.netflix.discovery.DiscoveryClient] -DiscoveryClient_BLOGROOM-CONSOLE/192.168.1.167:8091 - registration status: 204
2019-02-18 17:27:43.211 [user_provider] [main] WARN  [org.springframework.context.annotation.CommonAnnotationBeanPostProcessor] -Invocation of destroy method failed on bean with name 'scopedTarget.eurekaClient': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaInstanceConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
2019-02-18 17:27:43.212 [user_provider] [DiscoveryClient-InstanceInfoReplicator-0] WARN  [com.netflix.discovery.InstanceInfoReplicator] -There was a problem with the instance info replicator
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaInstanceConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:818)
	at org.springframework.beans.factory.support.ConstructorResolver.resolvePreparedArguments(ConstructorResolver.java:767)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:410)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:353)
	at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:390)
	at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:184)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:350)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:672)
	at com.netflix.appinfo.ApplicationInfoManager$$EnhancerBySpringCGLIB$$3883dd74.refreshDataCenterInfoIfRequired(<generated>)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1377)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-02-18 17:28:43.255 [user_provider] [main] INFO  [org.springframework.context.annotation.AnnotationConfigApplicationContext] -Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@37ceb1df: startup date [Mon Feb 18 17:28:43 CST 2019]; root of context hierarchy
2019-02-18 17:28:43.520 [user_provider] [main] INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] -JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-02-18 17:28:43.542 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$233eb882] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:28:43.884 [user_provider] [main] INFO  [cn.qyd.blogroom.console.ConsoleApp] -The following profiles are active: dev
2019-02-18 17:28:43.893 [user_provider] [main] INFO  [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext] -Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@55493582: startup date [Mon Feb 18 17:28:43 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@37ceb1df
2019-02-18 17:28:44.319 [user_provider] [main] INFO  [org.springframework.cloud.context.scope.GenericScope] -BeanFactory id=9979f664-36d6-3209-ab02-0281b97f306e
2019-02-18 17:28:44.329 [user_provider] [main] INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] -JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-02-18 17:28:44.378 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$233eb882] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:28:44.609 [user_provider] [main] INFO  [org.springframework.boot.web.embedded.tomcat.TomcatWebServer] -Tomcat initialized with port(s): 8091 (http)
2019-02-18 17:28:44.618 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Initializing ProtocolHandler ["http-nio-8091"]
2019-02-18 17:28:44.625 [user_provider] [main] INFO  [org.apache.catalina.core.StandardService] -Starting service [Tomcat]
2019-02-18 17:28:44.625 [user_provider] [main] INFO  [org.apache.catalina.core.StandardEngine] -Starting Servlet Engine: Apache Tomcat/8.5.32
2019-02-18 17:28:44.629 [user_provider] [localhost-startStop-1] INFO  [org.apache.catalina.core.AprLifecycleListener] -The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
2019-02-18 17:28:44.696 [user_provider] [localhost-startStop-1] INFO  [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]] -Initializing Spring embedded WebApplicationContext
2019-02-18 17:28:44.697 [user_provider] [localhost-startStop-1] INFO  [org.springframework.web.context.ContextLoader] -Root WebApplicationContext: initialization completed in 804 ms
2019-02-18 17:28:44.730 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.ServletRegistrationBean] -Servlet dispatcherServlet mapped to [/]
2019-02-18 17:28:44.733 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'characterEncodingFilter' to: [/*]
2019-02-18 17:28:44.734 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-02-18 17:28:44.734 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-02-18 17:28:44.734 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'requestContextFilter' to: [/*]
2019-02-18 17:28:44.790 [user_provider] [main] WARN  [com.netflix.config.sources.URLConfigurationSource] -No URLs will be polled as dynamic configuration sources.
2019-02-18 17:28:44.790 [user_provider] [main] INFO  [com.netflix.config.sources.URLConfigurationSource] -To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-02-18 17:28:44.792 [user_provider] [main] WARN  [com.netflix.config.sources.URLConfigurationSource] -No URLs will be polled as dynamic configuration sources.
2019-02-18 17:28:44.793 [user_provider] [main] INFO  [com.netflix.config.sources.URLConfigurationSource] -To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-02-18 17:28:44.872 [user_provider] [main] INFO  [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping] -Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-02-18 17:28:44.999 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter] -Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@55493582: startup date [Mon Feb 18 17:28:43 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@37ceb1df
2019-02-18 17:28:45.037 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/getAuthor],methods=[GET]}" onto public java.lang.String cn.qyd.blogroom.console.controller.TestController.getAuthor()
2019-02-18 17:28:45.038 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/getUser],methods=[GET]}" onto public java.lang.String cn.qyd.blogroom.console.controller.TestController.getUser()
2019-02-18 17:28:45.041 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-02-18 17:28:45.041 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-02-18 17:28:45.073 [user_provider] [main] INFO  [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping] -Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-02-18 17:28:45.073 [user_provider] [main] INFO  [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping] -Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-02-18 17:28:45.658 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Registering beans for JMX exposure on startup
2019-02-18 17:28:45.666 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2019-02-18 17:28:45.667 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Bean with name 'environmentManager' has been autodetected for JMX exposure
2019-02-18 17:28:45.668 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Bean with name 'refreshScope' has been autodetected for JMX exposure
2019-02-18 17:28:45.670 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2019-02-18 17:28:45.680 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2019-02-18 17:28:45.688 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=55493582,type=ConfigurationPropertiesRebinder]
2019-02-18 17:28:45.702 [user_provider] [main] INFO  [org.springframework.context.support.DefaultLifecycleProcessor] -Starting beans in phase 0
2019-02-18 17:28:45.713 [user_provider] [main] INFO  [org.springframework.cloud.netflix.eureka.InstanceInfoFactory] -Setting initial instance status as: STARTING
2019-02-18 17:28:45.741 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Initializing Eureka in region us-east-1
2019-02-18 17:28:45.909 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using JSON encoding codec LegacyJacksonJson
2019-02-18 17:28:45.909 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using JSON decoding codec LegacyJacksonJson
2019-02-18 17:28:45.998 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using XML encoding codec XStreamXml
2019-02-18 17:28:45.999 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using XML decoding codec XStreamXml
2019-02-18 17:28:46.153 [user_provider] [main] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:28:46.169 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Disable delta property : false
2019-02-18 17:28:46.169 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Single vip registry refresh property : null
2019-02-18 17:28:46.169 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Force full registry fetch : false
2019-02-18 17:28:46.169 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Application is null : false
2019-02-18 17:28:46.169 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Registered Applications size is zero : true
2019-02-18 17:28:46.169 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Application version is -1: true
2019-02-18 17:28:46.169 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Getting all instance registry info from the eureka server
2019-02-18 17:28:46.262 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -The response status is 200
2019-02-18 17:28:46.264 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Starting heartbeat executor: renew interval is: 30
2019-02-18 17:28:46.265 [user_provider] [main] INFO  [com.netflix.discovery.InstanceInfoReplicator] -InstanceInfoReplicator onDemand update allowed rate per min is 4
2019-02-18 17:28:46.268 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Discovery Client initialized at timestamp 1550482126267 with initial instances count: 2
2019-02-18 17:28:46.270 [user_provider] [main] INFO  [org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry] -Registering application BLOGROOM-CONSOLE with eureka with status UP
2019-02-18 17:28:46.271 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Saw local status change event StatusChangeEvent [timestamp=1550482126271, current=UP, previous=STARTING]
2019-02-18 17:28:46.272 [user_provider] [DiscoveryClient-InstanceInfoReplicator-0] INFO  [com.netflix.discovery.DiscoveryClient] -DiscoveryClient_BLOGROOM-CONSOLE/192.168.1.167:8091: registering service...
2019-02-18 17:28:46.283 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Starting ProtocolHandler ["http-nio-8091"]
2019-02-18 17:28:46.286 [user_provider] [main] ERROR [org.apache.catalina.core.StandardService] -Failed to start connector [Connector[HTTP/1.1-8091]]
org.apache.catalina.LifecycleException: Failed to start component [Connector[HTTP/1.1-8091]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:256)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:198)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:300)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at cn.qyd.blogroom.console.ConsoleApp.main(ConsoleApp.java:17)
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1020)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 13 common frames omitted
Caused by: java.net.BindException: 地址已在使用
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210)
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1150)
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:591)
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1018)
	... 14 common frames omitted
2019-02-18 17:28:46.290 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Pausing ProtocolHandler ["http-nio-8091"]
2019-02-18 17:28:46.291 [user_provider] [main] INFO  [org.apache.catalina.core.StandardService] -Stopping service [Tomcat]
2019-02-18 17:28:46.296 [user_provider] [main] INFO  [org.apache.catalina.util.LifecycleBase] -The stop() method was called on component [StandardServer[-1]] after stop() had already been called. The second call will be ignored.
2019-02-18 17:28:46.296 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Stopping ProtocolHandler ["http-nio-8091"]
2019-02-18 17:28:46.296 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Destroying ProtocolHandler ["http-nio-8091"]
2019-02-18 17:28:46.299 [user_provider] [main] INFO  [org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener] -

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-02-18 17:28:46.301 [user_provider] [main] ERROR [org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter] -

***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 8091 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 8091, or configure this application to listen on another port.

2019-02-18 17:28:46.302 [user_provider] [main] INFO  [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext] -Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@55493582: startup date [Mon Feb 18 17:28:43 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@37ceb1df
2019-02-18 17:28:46.303 [user_provider] [main] INFO  [org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry] -Unregistering application BLOGROOM-CONSOLE with eureka with status DOWN
2019-02-18 17:28:46.303 [user_provider] [main] WARN  [com.netflix.discovery.DiscoveryClient] -Saw local status change event StatusChangeEvent [timestamp=1550482126303, current=DOWN, previous=UP]
2019-02-18 17:28:46.303 [user_provider] [DiscoveryClient-InstanceInfoReplicator-0] INFO  [com.netflix.discovery.DiscoveryClient] -DiscoveryClient_BLOGROOM-CONSOLE/192.168.1.167:8091 - registration status: 204
2019-02-18 17:28:46.304 [user_provider] [DiscoveryClient-InstanceInfoReplicator-0] INFO  [com.netflix.discovery.DiscoveryClient] -DiscoveryClient_BLOGROOM-CONSOLE/192.168.1.167:8091: registering service...
2019-02-18 17:28:46.304 [user_provider] [main] INFO  [org.springframework.context.support.DefaultLifecycleProcessor] -Stopping beans in phase 0
2019-02-18 17:28:46.305 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Unregistering JMX-exposed beans on shutdown
2019-02-18 17:28:46.305 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Unregistering JMX-exposed beans
2019-02-18 17:28:46.308 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Shutting down DiscoveryClient ...
2019-02-18 17:28:46.309 [user_provider] [DiscoveryClient-InstanceInfoReplicator-0] INFO  [com.netflix.discovery.DiscoveryClient] -DiscoveryClient_BLOGROOM-CONSOLE/192.168.1.167:8091 - registration status: 204
2019-02-18 17:28:46.310 [user_provider] [main] WARN  [org.springframework.context.annotation.CommonAnnotationBeanPostProcessor] -Invocation of destroy method failed on bean with name 'scopedTarget.eurekaClient': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaInstanceConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
2019-02-18 17:29:33.474 [user_provider] [main] INFO  [org.springframework.context.annotation.AnnotationConfigApplicationContext] -Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@55fe41ea: startup date [Mon Feb 18 17:29:33 CST 2019]; root of context hierarchy
2019-02-18 17:29:33.810 [user_provider] [main] INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] -JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-02-18 17:29:33.852 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$657db82b] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:29:34.115 [user_provider] [main] INFO  [cn.qyd.blogroom.console.ConsoleApp] -The following profiles are active: dev
2019-02-18 17:29:34.126 [user_provider] [main] INFO  [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext] -Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@76a2ddf3: startup date [Mon Feb 18 17:29:34 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@55fe41ea
2019-02-18 17:29:34.603 [user_provider] [main] INFO  [org.springframework.cloud.context.scope.GenericScope] -BeanFactory id=9979f664-36d6-3209-ab02-0281b97f306e
2019-02-18 17:29:34.617 [user_provider] [main] INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] -JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-02-18 17:29:34.683 [user_provider] [main] INFO  [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] -Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$657db82b] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-18 17:29:34.892 [user_provider] [main] INFO  [org.springframework.boot.web.embedded.tomcat.TomcatWebServer] -Tomcat initialized with port(s): 8081 (http)
2019-02-18 17:29:34.901 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Initializing ProtocolHandler ["http-nio-8081"]
2019-02-18 17:29:34.908 [user_provider] [main] INFO  [org.apache.catalina.core.StandardService] -Starting service [Tomcat]
2019-02-18 17:29:34.908 [user_provider] [main] INFO  [org.apache.catalina.core.StandardEngine] -Starting Servlet Engine: Apache Tomcat/8.5.32
2019-02-18 17:29:34.911 [user_provider] [localhost-startStop-1] INFO  [org.apache.catalina.core.AprLifecycleListener] -The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
2019-02-18 17:29:34.997 [user_provider] [localhost-startStop-1] INFO  [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]] -Initializing Spring embedded WebApplicationContext
2019-02-18 17:29:34.998 [user_provider] [localhost-startStop-1] INFO  [org.springframework.web.context.ContextLoader] -Root WebApplicationContext: initialization completed in 872 ms
2019-02-18 17:29:35.031 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.ServletRegistrationBean] -Servlet dispatcherServlet mapped to [/]
2019-02-18 17:29:35.034 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'characterEncodingFilter' to: [/*]
2019-02-18 17:29:35.034 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-02-18 17:29:35.034 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-02-18 17:29:35.034 [user_provider] [localhost-startStop-1] INFO  [org.springframework.boot.web.servlet.FilterRegistrationBean] -Mapping filter: 'requestContextFilter' to: [/*]
2019-02-18 17:29:35.084 [user_provider] [main] WARN  [com.netflix.config.sources.URLConfigurationSource] -No URLs will be polled as dynamic configuration sources.
2019-02-18 17:29:35.084 [user_provider] [main] INFO  [com.netflix.config.sources.URLConfigurationSource] -To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-02-18 17:29:35.087 [user_provider] [main] WARN  [com.netflix.config.sources.URLConfigurationSource] -No URLs will be polled as dynamic configuration sources.
2019-02-18 17:29:35.087 [user_provider] [main] INFO  [com.netflix.config.sources.URLConfigurationSource] -To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-02-18 17:29:35.187 [user_provider] [main] INFO  [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping] -Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-02-18 17:29:35.309 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter] -Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@76a2ddf3: startup date [Mon Feb 18 17:29:34 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@55fe41ea
2019-02-18 17:29:35.343 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/getAuthor],methods=[GET]}" onto public java.lang.String cn.qyd.blogroom.console.controller.TestController.getAuthor()
2019-02-18 17:29:35.344 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/getUser],methods=[GET]}" onto public java.lang.String cn.qyd.blogroom.console.controller.TestController.getUser()
2019-02-18 17:29:35.347 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-02-18 17:29:35.348 [user_provider] [main] INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] -Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-02-18 17:29:35.365 [user_provider] [main] INFO  [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping] -Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-02-18 17:29:35.365 [user_provider] [main] INFO  [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping] -Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-02-18 17:29:35.931 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Registering beans for JMX exposure on startup
2019-02-18 17:29:35.939 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2019-02-18 17:29:35.939 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Bean with name 'environmentManager' has been autodetected for JMX exposure
2019-02-18 17:29:35.939 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Bean with name 'refreshScope' has been autodetected for JMX exposure
2019-02-18 17:29:35.941 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2019-02-18 17:29:35.950 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2019-02-18 17:29:35.956 [user_provider] [main] INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] -Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=76a2ddf3,type=ConfigurationPropertiesRebinder]
2019-02-18 17:29:35.962 [user_provider] [main] INFO  [org.springframework.context.support.DefaultLifecycleProcessor] -Starting beans in phase 0
2019-02-18 17:29:35.972 [user_provider] [main] INFO  [org.springframework.cloud.netflix.eureka.InstanceInfoFactory] -Setting initial instance status as: STARTING
2019-02-18 17:29:35.995 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Initializing Eureka in region us-east-1
2019-02-18 17:29:36.125 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using JSON encoding codec LegacyJacksonJson
2019-02-18 17:29:36.125 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using JSON decoding codec LegacyJacksonJson
2019-02-18 17:29:36.243 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using XML encoding codec XStreamXml
2019-02-18 17:29:36.243 [user_provider] [main] INFO  [com.netflix.discovery.provider.DiscoveryJerseyProvider] -Using XML decoding codec XStreamXml
2019-02-18 17:29:36.397 [user_provider] [main] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:29:36.407 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Disable delta property : false
2019-02-18 17:29:36.407 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Single vip registry refresh property : null
2019-02-18 17:29:36.407 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Force full registry fetch : false
2019-02-18 17:29:36.407 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Application is null : false
2019-02-18 17:29:36.407 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Registered Applications size is zero : true
2019-02-18 17:29:36.407 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Application version is -1: true
2019-02-18 17:29:36.407 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Getting all instance registry info from the eureka server
2019-02-18 17:29:36.526 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -The response status is 200
2019-02-18 17:29:36.528 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Starting heartbeat executor: renew interval is: 30
2019-02-18 17:29:36.530 [user_provider] [main] INFO  [com.netflix.discovery.InstanceInfoReplicator] -InstanceInfoReplicator onDemand update allowed rate per min is 4
2019-02-18 17:29:36.533 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Discovery Client initialized at timestamp 1550482176532 with initial instances count: 2
2019-02-18 17:29:36.536 [user_provider] [main] INFO  [org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry] -Registering application BLOGROOM-CONSOLE with eureka with status UP
2019-02-18 17:29:36.537 [user_provider] [main] INFO  [com.netflix.discovery.DiscoveryClient] -Saw local status change event StatusChangeEvent [timestamp=1550482176537, current=UP, previous=STARTING]
2019-02-18 17:29:36.538 [user_provider] [DiscoveryClient-InstanceInfoReplicator-0] INFO  [com.netflix.discovery.DiscoveryClient] -DiscoveryClient_BLOGROOM-CONSOLE/192.168.1.167:8081: registering service...
2019-02-18 17:29:36.551 [user_provider] [main] INFO  [org.apache.coyote.http11.Http11NioProtocol] -Starting ProtocolHandler ["http-nio-8081"]
2019-02-18 17:29:36.558 [user_provider] [main] INFO  [org.apache.tomcat.util.net.NioSelectorPool] -Using a shared selector for servlet write/read
2019-02-18 17:29:36.573 [user_provider] [DiscoveryClient-InstanceInfoReplicator-0] INFO  [com.netflix.discovery.DiscoveryClient] -DiscoveryClient_BLOGROOM-CONSOLE/192.168.1.167:8081 - registration status: 204
2019-02-18 17:29:36.577 [user_provider] [main] INFO  [org.springframework.boot.web.embedded.tomcat.TomcatWebServer] -Tomcat started on port(s): 8081 (http) with context path ''
2019-02-18 17:29:36.578 [user_provider] [main] INFO  [org.springframework.cloud.netflix.eureka.serviceregistry.EurekaAutoServiceRegistration] -Updating port to 8081
2019-02-18 17:29:36.580 [user_provider] [main] INFO  [cn.qyd.blogroom.console.ConsoleApp] -Started ConsoleApp in 3.993 seconds (JVM running for 4.657)
2019-02-18 17:29:36.581 [user_provider] [main] INFO  [cn.qyd.blogroom.console.ConsoleApp] -===================
2019-02-18 17:30:12.220 [user_provider] [http-nio-8081-exec-1] INFO  [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]] -Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-02-18 17:30:12.220 [user_provider] [http-nio-8081-exec-1] INFO  [org.springframework.web.servlet.DispatcherServlet] -FrameworkServlet 'dispatcherServlet': initialization started
2019-02-18 17:30:12.238 [user_provider] [http-nio-8081-exec-1] INFO  [org.springframework.web.servlet.DispatcherServlet] -FrameworkServlet 'dispatcherServlet': initialization completed in 18 ms
2019-02-18 17:30:24.024 [user_provider] [http-nio-8081-exec-4] INFO  [org.springframework.context.annotation.AnnotationConfigApplicationContext] -Refreshing SpringClientFactory-user-provider: startup date [Mon Feb 18 17:30:24 CST 2019]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@76a2ddf3
2019-02-18 17:30:24.087 [user_provider] [http-nio-8081-exec-4] INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] -JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-02-18 17:30:24.289 [user_provider] [http-nio-8081-exec-4] INFO  [com.netflix.config.ChainedDynamicProperty] -Flipping property: user-provider.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2019-02-18 17:30:24.299 [user_provider] [http-nio-8081-exec-4] INFO  [com.netflix.util.concurrent.ShutdownEnabledTimer] -Shutdown hook installed for: NFLoadBalancer-PingTimer-user-provider
2019-02-18 17:30:24.313 [user_provider] [http-nio-8081-exec-4] INFO  [com.netflix.loadbalancer.BaseLoadBalancer] -Client: user-provider instantiated a LoadBalancer: DynamicServerListLoadBalancer:{NFLoadBalancer:name=user-provider,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
2019-02-18 17:30:24.317 [user_provider] [http-nio-8081-exec-4] INFO  [com.netflix.loadbalancer.DynamicServerListLoadBalancer] -Using serverListUpdater PollingServerListUpdater
2019-02-18 17:30:24.341 [user_provider] [http-nio-8081-exec-4] INFO  [com.netflix.config.ChainedDynamicProperty] -Flipping property: user-provider.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2019-02-18 17:30:24.343 [user_provider] [http-nio-8081-exec-4] INFO  [com.netflix.loadbalancer.DynamicServerListLoadBalancer] -DynamicServerListLoadBalancer for client user-provider initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=user-provider,current list of Servers=[192.168.1.167:8091],Load balancer stats=Zone stats: {defaultzone=[Zone:defaultzone;	Instance count:1;	Active connections count: 0;	Circuit breaker tripped count: 0;	Active connections per server: 0.0;]
},Server stats: [[Server:192.168.1.167:8091;	Zone:defaultZone;	Total Requests:0;	Successive connection failure:0;	Total blackout seconds:0;	Last connection made:Thu Jan 01 08:00:00 CST 1970;	First connection made: Thu Jan 01 08:00:00 CST 1970;	Active Connections:0;	total failure count in last (1000) msecs:0;	average resp time:0.0;	90 percentile resp time:0.0;	95 percentile resp time:0.0;	min resp time:0.0;	max resp time:0.0;	stddev resp time:0.0]
]}ServerList:org.springframework.cloud.netflix.ribbon.eureka.DomainExtractingServerList@6cfa7f61
2019-02-18 17:30:25.321 [user_provider] [PollingServerListUpdater-0] INFO  [com.netflix.config.ChainedDynamicProperty] -Flipping property: user-provider.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2019-02-18 17:30:47.856 [user_provider] [AsyncResolver-bootstrap-executor-0] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:34:36.409 [user_provider] [AsyncResolver-bootstrap-executor-0] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:35:47.857 [user_provider] [AsyncResolver-bootstrap-executor-0] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:39:36.410 [user_provider] [AsyncResolver-bootstrap-executor-0] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:40:47.858 [user_provider] [AsyncResolver-bootstrap-executor-0] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:44:36.411 [user_provider] [AsyncResolver-bootstrap-executor-0] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:45:47.859 [user_provider] [AsyncResolver-bootstrap-executor-0] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:49:36.412 [user_provider] [AsyncResolver-bootstrap-executor-0] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:50:47.861 [user_provider] [AsyncResolver-bootstrap-executor-0] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:54:36.413 [user_provider] [AsyncResolver-bootstrap-executor-0] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
2019-02-18 17:55:47.862 [user_provider] [AsyncResolver-bootstrap-executor-0] INFO  [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver] -Resolving eureka endpoints via configuration
